# Generated by Django 4.2 on 2026-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_emailverification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exception_type', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('file_name', models.CharField(max_length=500, null=True)),
                ('line_number', models.IntegerField(null=True)),
                ('url_path', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Log خطای سرور',
                'verbose_name_plural': 'Logهای خطای سرور',
                'ordering': ['-timestamp'],
            },
        ),
    ]
