# Generated by Django 4.2 on 2026-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_service_servicefeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
