# Generated by Django 4.2 on 2026-02-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_servererrorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
